---
  .travis.yml:
    hc_secure: "GJ+zaKowNLqvc1Yb4+CHyF2sm/tyiUxJvq5NwJOmg5uCSjPE1WYi44b2gokgfbpXACr2G+HNRKTEEUtjqcya/LYWdiRPE25qJWDpNaJ9mo+4lxFzVg4TmNlmg4mm4sByDXYeVYhGDKo/KyCxVXwyMZp+XBU7y0euAkIx3wxoeoc="
